CREATE TABLE Users (
    UserID NUMBER PRIMARY KEY,
    Username VARCHAR2(100) NOT NULL,
    Email VARCHAR2(150) UNIQUE NOT NULL CHECK (Email LIKE '%@%.%'),
    Phone VARCHAR2(15) NOT NULL,
    Password VARCHAR2(25) NOT NULL,
    Prev_Password VARCHAR2(25),
    otp NUMBER,
    CreatedAt DATE DEFAULT SYSDATE,
    LastLogin DATE DEFAULT SYSDATE
);

CREATE SEQUENCE seq_user_id
START WITH 1
INCREMENT BY 1
NOCACHE;
